---
version: 2
updates:
  - package-ecosystem: {{ cookiecutter.package_manager }}
    directory: /
    schedule:
      interval: daily
    labels:
      - {{ cookiecutter.package_manager }} dependencies
      - triage-board
