[tool.poetry]
name = "poetry-cookiecutter"
version = "0.1.0"
description = "Project template for applications using Poetry."
authors = ["Jesse P. Johnson"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"
cookiecutter = "^1.7.2"

[tool.poetry.dev-dependencies]
pytest = "<6.0.0"
pytest-cookies = "^0.5.1"
invoke = "^1.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
